server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    root /var/www/wg-captive-portal;
    index index.html;

    add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate" always;
    add_header Pragma "no-cache" always;
    add_header Expires "0" always;

    location / {
        try_files /index.html =404;
    }
}

